"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lambda_cloud_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class APIErrorUnauthorizedTypedDict(TypedDict):
    code: NotRequired[str]
    r"""The unique identifier for the type of error."""
    message: NotRequired[str]
    r"""A description of the error."""
    suggestion: NotRequired[str]
    r"""One or more suggestions of possible ways to fix the error."""


class APIErrorUnauthorized(BaseModel):
    code: Optional[str] = "global/invalid-api-key"
    r"""The unique identifier for the type of error."""

    message: Optional[str] = "API key was invalid, expired, or deleted."
    r"""A description of the error."""

    suggestion: Optional[str] = (
        "Check your API key or create a new one, then try again."
    )
    r"""One or more suggestions of possible ways to fix the error."""
