"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lambda_cloud_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class APIErrorLaunchResourceNotFoundTypedDict(TypedDict):
    message: str
    r"""The resource the API was unable to find."""
    suggestion: str
    r"""One or more suggestions of possible ways to fix the error."""
    code: NotRequired[str]
    r"""The unique identifier for the type of error."""


class APIErrorLaunchResourceNotFound(BaseModel):
    message: str
    r"""The resource the API was unable to find."""

    suggestion: str
    r"""One or more suggestions of possible ways to fix the error."""

    code: Optional[str] = "global/object-does-not-exist"
    r"""The unique identifier for the type of error."""
