"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lambda_cloud_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class APIErrorAccountInactiveTypedDict(TypedDict):
    code: NotRequired[str]
    r"""The unique identifier for the type of error."""
    message: NotRequired[str]
    r"""A description of the error."""
    suggestion: NotRequired[str]
    r"""One or more suggestions of possible ways to fix the error."""


class APIErrorAccountInactive(BaseModel):
    code: Optional[str] = "global/account-inactive"
    r"""The unique identifier for the type of error."""

    message: Optional[str] = "Your account is inactive."
    r"""A description of the error."""

    suggestion: Optional[str] = (
        "Make sure you have verified your email address and have a valid payment method. Contact Support if problems continue."
    )
    r"""One or more suggestions of possible ways to fix the error."""
