"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lambda_cloud_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class APIErrorInvalidBillingAddressTypedDict(TypedDict):
    code: NotRequired[str]
    r"""The unique identifier for the type of error."""
    message: NotRequired[str]
    r"""A description of the error."""
    suggestion: NotRequired[str]
    r"""One or more suggestions of possible ways to fix the error."""


class APIErrorInvalidBillingAddress(BaseModel):
    code: Optional[str] = "global/invalid-address"
    r"""The unique identifier for the type of error."""

    message: Optional[str] = "Your billing address is invalid."
    r"""A description of the error."""

    suggestion: Optional[str] = (
        "Make sure your billing address is valid. Contact Support if problems continue."
    )
    r"""One or more suggestions of possible ways to fix the error."""
