"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apierroraccountinactive import APIErrorAccountInactive
from .apierrorinvalidparameters import APIErrorInvalidParameters
from .apierrorunauthorized import APIErrorUnauthorized
from .emptyresponse import EmptyResponse, EmptyResponseTypedDict
from .schemebasicauth import SchemeBasicAuth, SchemeBasicAuthTypedDict
from lambda_cloud_sdk import utils
from lambda_cloud_sdk.types import BaseModel
from lambda_cloud_sdk.utils import FieldMetadata, PathParamMetadata, SecurityMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteSSHKeySecurityTypedDict(TypedDict):
    basic_auth: NotRequired[SchemeBasicAuthTypedDict]
    bearer_auth: NotRequired[str]


class DeleteSSHKeySecurity(BaseModel):
    basic_auth: Annotated[
        Optional[SchemeBasicAuth],
        FieldMetadata(
            security=SecurityMetadata(scheme=True, scheme_type="http", sub_type="basic")
        ),
    ] = None

    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None


class DeleteSSHKeyRequestTypedDict(TypedDict):
    id: str


class DeleteSSHKeyRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class DeleteSSHKeySSHKeysResponseResponseBodyData(BaseModel):
    error: APIErrorAccountInactive


class DeleteSSHKeySSHKeysResponseResponseBody(Exception):
    r"""Forbidden"""

    data: DeleteSSHKeySSHKeysResponseResponseBodyData

    def __init__(self, data: DeleteSSHKeySSHKeysResponseResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, DeleteSSHKeySSHKeysResponseResponseBodyData
        )


class DeleteSSHKeySSHKeysResponseBodyData(BaseModel):
    error: APIErrorUnauthorized


class DeleteSSHKeySSHKeysResponseBody(Exception):
    r"""Unauthorized"""

    data: DeleteSSHKeySSHKeysResponseBodyData

    def __init__(self, data: DeleteSSHKeySSHKeysResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, DeleteSSHKeySSHKeysResponseBodyData)


class DeleteSSHKeySSHKeysResponse400ResponseBodyData(BaseModel):
    error: APIErrorInvalidParameters


class DeleteSSHKeySSHKeysResponse400ResponseBody(Exception):
    r"""Bad Request"""

    data: DeleteSSHKeySSHKeysResponse400ResponseBodyData

    def __init__(self, data: DeleteSSHKeySSHKeysResponse400ResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, DeleteSSHKeySSHKeysResponse400ResponseBodyData
        )


class DeleteSSHKeyResponseBodyTypedDict(TypedDict):
    r"""OK"""

    data: EmptyResponseTypedDict


class DeleteSSHKeyResponseBody(BaseModel):
    r"""OK"""

    data: EmptyResponse
