"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .region import Region, RegionTypedDict
from .user import User, UserTypedDict
from datetime import datetime
from lambda_cloud_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class FilesystemTypedDict(TypedDict):
    r"""Information about a shared filesystem."""

    id: str
    r"""The unique identifier (ID) of the filesystem."""
    name: str
    r"""The name of the filesystem."""
    mount_point: str
    r"""The absolute path indicating where on instances the filesystem will be mounted."""
    created: datetime
    r"""The date and time at which the filesystem was created. Formatted as an ISO 8601 timestamp."""
    created_by: UserTypedDict
    r"""Information about a user in your Team."""
    is_in_use: bool
    r"""Whether the filesystem is currently in use by an instance. Filesystems that
    are in use cannot be deleted.
    """
    region: RegionTypedDict
    bytes_used: NotRequired[int]
    r"""The approximate amount of storage used by the filesystem in bytes. This estimate is
    updated every few hours.
    """


class Filesystem(BaseModel):
    r"""Information about a shared filesystem."""

    id: str
    r"""The unique identifier (ID) of the filesystem."""

    name: str
    r"""The name of the filesystem."""

    mount_point: str
    r"""The absolute path indicating where on instances the filesystem will be mounted."""

    created: datetime
    r"""The date and time at which the filesystem was created. Formatted as an ISO 8601 timestamp."""

    created_by: User
    r"""Information about a user in your Team."""

    is_in_use: bool
    r"""Whether the filesystem is currently in use by an instance. Filesystems that
    are in use cannot be deleted.
    """

    region: Region

    bytes_used: Optional[int] = None
    r"""The approximate amount of storage used by the filesystem in bytes. This estimate is
    updated every few hours.
    """
