"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lambda_cloud_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class FilesystemDeleteResponseTypedDict(TypedDict):
    deleted_ids: List[str]
    r"""The unique identifiers of the filesystems that were deleted."""


class FilesystemDeleteResponse(BaseModel):
    deleted_ids: List[str]
    r"""The unique identifiers of the filesystems that were deleted."""
