"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .publicregioncode import PublicRegionCode
from lambda_cloud_sdk.types import BaseModel
from typing_extensions import TypedDict


class FilesystemCreateRequestTypedDict(TypedDict):
    name: str
    r"""The name of the filesystem."""
    region: PublicRegionCode


class FilesystemCreateRequest(BaseModel):
    name: str
    r"""The name of the filesystem."""

    region: PublicRegionCode
