"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apierroraccountinactive import APIErrorAccountInactive
from .apierrorunauthorized import APIErrorUnauthorized
from .firewallrule import FirewallRule, FirewallRuleTypedDict
from .schemebasicauth import SchemeBasicAuth, SchemeBasicAuthTypedDict
from lambda_cloud_sdk import utils
from lambda_cloud_sdk.types import BaseModel
from lambda_cloud_sdk.utils import FieldMetadata, SecurityMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FirewallRulesListSecurityTypedDict(TypedDict):
    basic_auth: NotRequired[SchemeBasicAuthTypedDict]
    bearer_auth: NotRequired[str]


class FirewallRulesListSecurity(BaseModel):
    basic_auth: Annotated[
        Optional[SchemeBasicAuth],
        FieldMetadata(
            security=SecurityMetadata(scheme=True, scheme_type="http", sub_type="basic")
        ),
    ] = None

    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None


class FirewallRulesListFirewallsResponseResponseBodyData(BaseModel):
    error: APIErrorAccountInactive


class FirewallRulesListFirewallsResponseResponseBody(Exception):
    r"""Forbidden"""

    data: FirewallRulesListFirewallsResponseResponseBodyData

    def __init__(self, data: FirewallRulesListFirewallsResponseResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, FirewallRulesListFirewallsResponseResponseBodyData
        )


class FirewallRulesListFirewallsResponseBodyData(BaseModel):
    error: APIErrorUnauthorized


class FirewallRulesListFirewallsResponseBody(Exception):
    r"""Unauthorized"""

    data: FirewallRulesListFirewallsResponseBodyData

    def __init__(self, data: FirewallRulesListFirewallsResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, FirewallRulesListFirewallsResponseBodyData)


class FirewallRulesListResponseBodyTypedDict(TypedDict):
    r"""OK"""

    data: List[FirewallRuleTypedDict]


class FirewallRulesListResponseBody(BaseModel):
    r"""OK"""

    data: List[FirewallRule]
