"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .firewallrule import FirewallRule, FirewallRuleTypedDict
from lambda_cloud_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class FirewallRulesPutRequestTypedDict(TypedDict):
    data: List[FirewallRuleTypedDict]
    r"""The list of inbound firewall rules."""


class FirewallRulesPutRequest(BaseModel):
    data: List[FirewallRule]
    r"""The list of inbound firewall rules."""
