"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apierroraccountinactive import APIErrorAccountInactive
from .apierrorunauthorized import APIErrorUnauthorized
from .firewallrule import FirewallRule, FirewallRuleTypedDict
from .schemebasicauth import SchemeBasicAuth, SchemeBasicAuthTypedDict
from lambda_cloud_sdk import utils
from lambda_cloud_sdk.types import BaseModel
from lambda_cloud_sdk.utils import FieldMetadata, SecurityMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FirewallRulesSetSecurityTypedDict(TypedDict):
    basic_auth: NotRequired[SchemeBasicAuthTypedDict]
    bearer_auth: NotRequired[str]


class FirewallRulesSetSecurity(BaseModel):
    basic_auth: Annotated[
        Optional[SchemeBasicAuth],
        FieldMetadata(
            security=SecurityMetadata(scheme=True, scheme_type="http", sub_type="basic")
        ),
    ] = None

    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None


class FirewallRulesSetFirewallsResponseResponseBodyData(BaseModel):
    error: APIErrorAccountInactive


class FirewallRulesSetFirewallsResponseResponseBody(Exception):
    r"""Forbidden"""

    data: FirewallRulesSetFirewallsResponseResponseBodyData

    def __init__(self, data: FirewallRulesSetFirewallsResponseResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, FirewallRulesSetFirewallsResponseResponseBodyData
        )


class FirewallRulesSetFirewallsResponseBodyData(BaseModel):
    error: APIErrorUnauthorized


class FirewallRulesSetFirewallsResponseBody(Exception):
    r"""Unauthorized"""

    data: FirewallRulesSetFirewallsResponseBodyData

    def __init__(self, data: FirewallRulesSetFirewallsResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, FirewallRulesSetFirewallsResponseBodyData)


class FirewallRulesSetResponseBodyTypedDict(TypedDict):
    r"""OK"""

    data: List[FirewallRuleTypedDict]


class FirewallRulesSetResponseBody(BaseModel):
    r"""OK"""

    data: List[FirewallRule]
