"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lambda_cloud_sdk.types import BaseModel
from typing_extensions import TypedDict


class GeneratedSSHKeyTypedDict(TypedDict):
    r"""Information about a server-generated SSH key, which can be used to access instances over
    SSH.
    """

    id: str
    r"""The unique identifier (ID) of the SSH key."""
    name: str
    r"""The name of the SSH key."""
    public_key: str
    r"""The public key for the SSH key."""
    private_key: str
    r"""The private key generated in the SSH key pair. Make sure to store a
    copy of this key locally, as Lambda does not store the key server-side.
    """


class GeneratedSSHKey(BaseModel):
    r"""Information about a server-generated SSH key, which can be used to access instances over
    SSH.
    """

    id: str
    r"""The unique identifier (ID) of the SSH key."""

    name: str
    r"""The name of the SSH key."""

    public_key: str
    r"""The public key for the SSH key."""

    private_key: str
    r"""The private key generated in the SSH key pair. Make sure to store a
    copy of this key locally, as Lambda does not store the key server-side.
    """
