"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .imagearchitecture import ImageArchitecture
from .region import Region, RegionTypedDict
from datetime import datetime
from lambda_cloud_sdk.types import BaseModel
from typing_extensions import TypedDict


class ImageTypedDict(TypedDict):
    r"""An available machine image in Lambda Cloud."""

    id: str
    r"""The unique identifier (ID) for an image."""
    created_time: datetime
    r"""The date and time that the image was created."""
    updated_time: datetime
    r"""The date and time that the image was last updated."""
    name: str
    r"""The human-readable identifier for an image."""
    description: str
    r"""Additional information about the image."""
    family: str
    r"""The family the image belongs to."""
    version: str
    r"""The image version."""
    architecture: ImageArchitecture
    region: RegionTypedDict


class Image(BaseModel):
    r"""An available machine image in Lambda Cloud."""

    id: str
    r"""The unique identifier (ID) for an image."""

    created_time: datetime
    r"""The date and time that the image was created."""

    updated_time: datetime
    r"""The date and time that the image was last updated."""

    name: str
    r"""The human-readable identifier for an image."""

    description: str
    r"""Additional information about the image."""

    family: str
    r"""The family the image belongs to."""

    version: str
    r"""The image version."""

    architecture: ImageArchitecture

    region: Region
