"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ImageArchitecture(str, Enum):
    X86_64 = "x86_64"
    ARM64 = "arm64"
