"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lambda_cloud_sdk.types import BaseModel
from typing_extensions import TypedDict


class ImageSpecificationFamilyTypedDict(TypedDict):
    r"""Specifies the image to use by its family name."""

    family: str
    r"""The family name of the image."""


class ImageSpecificationFamily(BaseModel):
    r"""Specifies the image to use by its family name."""

    family: str
    r"""The family name of the image."""
