"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lambda_cloud_sdk.types import BaseModel
from typing_extensions import TypedDict


class InstanceTypeSpecsTypedDict(TypedDict):
    vcpus: int
    r"""The number of virtual CPUs."""
    memory_gib: int
    r"""The amount of RAM in gibibytes (GiB)."""
    storage_gib: int
    r"""The amount of storage in gibibytes (GiB)."""
    gpus: int
    r"""The number of GPUs."""


class InstanceTypeSpecs(BaseModel):
    vcpus: int
    r"""The number of virtual CPUs."""

    memory_gib: int
    r"""The amount of RAM in gibibytes (GiB)."""

    storage_gib: int
    r"""The amount of storage in gibibytes (GiB)."""

    gpus: int
    r"""The number of GPUs."""
