"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class InstanceStatus(str, Enum):
    r"""The current status of the instance."""

    BOOTING = "booting"
    ACTIVE = "active"
    UNHEALTHY = "unhealthy"
    TERMINATED = "terminated"
    TERMINATING = "terminating"
