"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .instanceactionavailability import (
    InstanceActionAvailability,
    InstanceActionAvailabilityTypedDict,
)
from .instancestatus import InstanceStatus
from .instancetype import InstanceType, InstanceTypeTypedDict
from .region import Region, RegionTypedDict
from lambda_cloud_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class InstanceTypedDict(TypedDict):
    r"""Detailed information about the instance."""

    id: str
    r"""The unique identifier of the instance."""
    status: InstanceStatus
    r"""The current status of the instance."""
    ssh_key_names: List[str]
    r"""The names of the SSH keys that are allowed to access the instance."""
    file_system_names: List[str]
    r"""The names of the filesystems attached to the instance. If no filesystems are attached, this array is empty."""
    region: RegionTypedDict
    instance_type: InstanceTypeTypedDict
    actions: InstanceActionAvailabilityTypedDict
    name: NotRequired[str]
    r"""If set, the user-provided name of the instance."""
    ip: NotRequired[str]
    r"""The public IPv4 address of the instance."""
    private_ip: NotRequired[str]
    r"""The private IPv4 address of the instance."""
    hostname: NotRequired[str]
    r"""The hostname assigned to this instance, which resolves to the instance's IP."""
    jupyter_token: NotRequired[str]
    r"""The secret token used to log into the JupyterLab server hosted on the instance."""
    jupyter_url: NotRequired[str]
    r"""The URL that opens the JupyterLab environment on the instance."""


class Instance(BaseModel):
    r"""Detailed information about the instance."""

    id: str
    r"""The unique identifier of the instance."""

    status: InstanceStatus
    r"""The current status of the instance."""

    ssh_key_names: List[str]
    r"""The names of the SSH keys that are allowed to access the instance."""

    file_system_names: List[str]
    r"""The names of the filesystems attached to the instance. If no filesystems are attached, this array is empty."""

    region: Region

    instance_type: InstanceType

    actions: InstanceActionAvailability

    name: Optional[str] = None
    r"""If set, the user-provided name of the instance."""

    ip: Optional[str] = None
    r"""The public IPv4 address of the instance."""

    private_ip: Optional[str] = None
    r"""The private IPv4 address of the instance."""

    hostname: Optional[str] = None
    r"""The hostname assigned to this instance, which resolves to the instance's IP."""

    jupyter_token: Optional[str] = None
    r"""The secret token used to log into the JupyterLab server hosted on the instance."""

    jupyter_url: Optional[str] = None
    r"""The URL that opens the JupyterLab environment on the instance."""
