"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .instancetypespecs import InstanceTypeSpecs, InstanceTypeSpecsTypedDict
from lambda_cloud_sdk.types import BaseModel
from typing_extensions import TypedDict


class InstanceTypeTypedDict(TypedDict):
    name: str
    r"""The name of the instance type."""
    description: str
    r"""A description of the instance type."""
    gpu_description: str
    r"""The type of GPU used by this instance type."""
    price_cents_per_hour: int
    r"""The price of the instance type in US cents per hour."""
    specs: InstanceTypeSpecsTypedDict


class InstanceType(BaseModel):
    name: str
    r"""The name of the instance type."""

    description: str
    r"""A description of the instance type."""

    gpu_description: str
    r"""The type of GPU used by this instance type."""

    price_cents_per_hour: int
    r"""The price of the instance type in US cents per hour."""

    specs: InstanceTypeSpecs
