"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lambda_cloud_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class InstanceRestartRequestTypedDict(TypedDict):
    instance_ids: List[str]
    r"""The unique identifiers (IDs) of the instances to restart."""


class InstanceRestartRequest(BaseModel):
    instance_ids: List[str]
    r"""The unique identifiers (IDs) of the instances to restart."""
