"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .instance import Instance, InstanceTypedDict
from lambda_cloud_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class InstanceTerminateResponseTypedDict(TypedDict):
    terminated_instances: List[InstanceTypedDict]
    r"""The list of instances that were successfully terminated."""


class InstanceTerminateResponse(BaseModel):
    terminated_instances: List[Instance]
    r"""The list of instances that were successfully terminated."""
