"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class InstanceActionUnavailableCode(str, Enum):
    VM_HAS_NOT_LAUNCHED = "vm-has-not-launched"
    VM_IS_TOO_OLD = "vm-is-too-old"
    VM_IS_TERMINATING = "vm-is-terminating"
