"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .instancetype import InstanceType, InstanceTypeTypedDict
from .region import Region, RegionTypedDict
from lambda_cloud_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class InstanceTypesItemTypedDict(TypedDict):
    r"""Detailed information and regional availability for the instance type."""

    instance_type: InstanceTypeTypedDict
    regions_with_capacity_available: List[RegionTypedDict]
    r"""A list of the regions in which this instance type is available."""


class InstanceTypesItem(BaseModel):
    r"""Detailed information and regional availability for the instance type."""

    instance_type: InstanceType

    regions_with_capacity_available: List[Region]
    r"""A list of the regions in which this instance type is available."""
