"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .instanceactionavailabilitydetails import (
    InstanceActionAvailabilityDetails,
    InstanceActionAvailabilityDetailsTypedDict,
)
from lambda_cloud_sdk.types import BaseModel
from typing_extensions import TypedDict


class InstanceActionAvailabilityTypedDict(TypedDict):
    migrate: InstanceActionAvailabilityDetailsTypedDict
    rebuild: InstanceActionAvailabilityDetailsTypedDict
    restart: InstanceActionAvailabilityDetailsTypedDict
    cold_reboot: InstanceActionAvailabilityDetailsTypedDict
    terminate: InstanceActionAvailabilityDetailsTypedDict


class InstanceActionAvailability(BaseModel):
    migrate: InstanceActionAvailabilityDetails

    rebuild: InstanceActionAvailabilityDetails

    restart: InstanceActionAvailabilityDetails

    cold_reboot: InstanceActionAvailabilityDetails

    terminate: InstanceActionAvailabilityDetails
