"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apierroraccountinactive import APIErrorAccountInactive
from .apierrorunauthorized import APIErrorUnauthorized
from .schemebasicauth import SchemeBasicAuth, SchemeBasicAuthTypedDict
from .sshkey import SSHKey, SSHKeyTypedDict
from lambda_cloud_sdk import utils
from lambda_cloud_sdk.types import BaseModel
from lambda_cloud_sdk.utils import FieldMetadata, SecurityMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListSSHKeysSecurityTypedDict(TypedDict):
    basic_auth: NotRequired[SchemeBasicAuthTypedDict]
    bearer_auth: NotRequired[str]


class ListSSHKeysSecurity(BaseModel):
    basic_auth: Annotated[
        Optional[SchemeBasicAuth],
        FieldMetadata(
            security=SecurityMetadata(scheme=True, scheme_type="http", sub_type="basic")
        ),
    ] = None

    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None


class ListSSHKeysSSHKeysResponseResponseBodyData(BaseModel):
    error: APIErrorAccountInactive


class ListSSHKeysSSHKeysResponseResponseBody(Exception):
    r"""Forbidden"""

    data: ListSSHKeysSSHKeysResponseResponseBodyData

    def __init__(self, data: ListSSHKeysSSHKeysResponseResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, ListSSHKeysSSHKeysResponseResponseBodyData)


class ListSSHKeysSSHKeysResponseBodyData(BaseModel):
    error: APIErrorUnauthorized


class ListSSHKeysSSHKeysResponseBody(Exception):
    r"""Unauthorized"""

    data: ListSSHKeysSSHKeysResponseBodyData

    def __init__(self, data: ListSSHKeysSSHKeysResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, ListSSHKeysSSHKeysResponseBodyData)


class ListSSHKeysResponseBodyTypedDict(TypedDict):
    r"""OK"""

    data: List[SSHKeyTypedDict]


class ListSSHKeysResponseBody(BaseModel):
    r"""OK"""

    data: List[SSHKey]
