"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apierroraccountinactive import APIErrorAccountInactive
from .apierrorunauthorized import APIErrorUnauthorized
from .image import Image, ImageTypedDict
from .schemebasicauth import SchemeBasicAuth, SchemeBasicAuthTypedDict
from lambda_cloud_sdk import utils
from lambda_cloud_sdk.types import BaseModel
from lambda_cloud_sdk.utils import FieldMetadata, SecurityMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListImagesSecurityTypedDict(TypedDict):
    basic_auth: NotRequired[SchemeBasicAuthTypedDict]
    bearer_auth: NotRequired[str]


class ListImagesSecurity(BaseModel):
    basic_auth: Annotated[
        Optional[SchemeBasicAuth],
        FieldMetadata(
            security=SecurityMetadata(scheme=True, scheme_type="http", sub_type="basic")
        ),
    ] = None

    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None


class ListImagesImagesResponseResponseBodyData(BaseModel):
    error: APIErrorAccountInactive


class ListImagesImagesResponseResponseBody(Exception):
    r"""Forbidden"""

    data: ListImagesImagesResponseResponseBodyData

    def __init__(self, data: ListImagesImagesResponseResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, ListImagesImagesResponseResponseBodyData)


class ListImagesImagesResponseBodyData(BaseModel):
    error: APIErrorUnauthorized


class ListImagesImagesResponseBody(Exception):
    r"""Unauthorized"""

    data: ListImagesImagesResponseBodyData

    def __init__(self, data: ListImagesImagesResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, ListImagesImagesResponseBodyData)


class ListImagesResponseBodyTypedDict(TypedDict):
    r"""OK"""

    data: List[ImageTypedDict]


class ListImagesResponseBody(BaseModel):
    r"""OK"""

    data: List[Image]
