"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apierroraccountinactive import APIErrorAccountInactive
from .apierrorinstancenotfound import APIErrorInstanceNotFound
from .apierrorunauthorized import APIErrorUnauthorized
from .instanceterminateresponse import (
    InstanceTerminateResponse,
    InstanceTerminateResponseTypedDict,
)
from .schemebasicauth import SchemeBasicAuth, SchemeBasicAuthTypedDict
from lambda_cloud_sdk import utils
from lambda_cloud_sdk.types import BaseModel
from lambda_cloud_sdk.utils import FieldMetadata, SecurityMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TerminateInstanceSecurityTypedDict(TypedDict):
    basic_auth: NotRequired[SchemeBasicAuthTypedDict]
    bearer_auth: NotRequired[str]


class TerminateInstanceSecurity(BaseModel):
    basic_auth: Annotated[
        Optional[SchemeBasicAuth],
        FieldMetadata(
            security=SecurityMetadata(scheme=True, scheme_type="http", sub_type="basic")
        ),
    ] = None

    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None


class TerminateInstanceInstancesResponse404ResponseBodyData(BaseModel):
    error: APIErrorInstanceNotFound


class TerminateInstanceInstancesResponse404ResponseBody(Exception):
    r"""Not Found"""

    data: TerminateInstanceInstancesResponse404ResponseBodyData

    def __init__(self, data: TerminateInstanceInstancesResponse404ResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, TerminateInstanceInstancesResponse404ResponseBodyData
        )


class TerminateInstanceInstancesResponseResponseBodyData(BaseModel):
    error: APIErrorAccountInactive


class TerminateInstanceInstancesResponseResponseBody(Exception):
    r"""Forbidden"""

    data: TerminateInstanceInstancesResponseResponseBodyData

    def __init__(self, data: TerminateInstanceInstancesResponseResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, TerminateInstanceInstancesResponseResponseBodyData
        )


class TerminateInstanceInstancesResponseBodyData(BaseModel):
    error: APIErrorUnauthorized


class TerminateInstanceInstancesResponseBody(Exception):
    r"""Unauthorized"""

    data: TerminateInstanceInstancesResponseBodyData

    def __init__(self, data: TerminateInstanceInstancesResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, TerminateInstanceInstancesResponseBodyData)


class TerminateInstanceResponseBodyTypedDict(TypedDict):
    r"""OK"""

    data: InstanceTerminateResponseTypedDict


class TerminateInstanceResponseBody(BaseModel):
    r"""OK"""

    data: InstanceTerminateResponse
