"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .userstatus import UserStatus
from lambda_cloud_sdk.types import BaseModel
from typing_extensions import TypedDict


class UserTypedDict(TypedDict):
    r"""Information about a user in your Team."""

    id: str
    r"""The unique identifier for the user."""
    email: str
    r"""The email address of the user."""
    status: UserStatus
    r"""Status of the user's account."""


class User(BaseModel):
    r"""Information about a user in your Team."""

    id: str
    r"""The unique identifier for the user."""

    email: str
    r"""The email address of the user."""

    status: UserStatus
    r"""Status of the user's account."""
