"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class UserStatus(str, Enum):
    r"""Status of the user's account."""

    ACTIVE = "active"
    DEACTIVATED = "deactivated"
